spring:
  application:
    name: date-me
  datasource:
    url: jdbc:postgresql://localhost:5430/date-me
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
    placeholder-replacement: false

storage:
  s3:
    credentials:
      access-key: accessKey
      secret-key: secretKey
    bucket: date-me
    stuck:
      auto: false
    region:
      static: us-east-1
